In [4]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/PramodShenoy/911-Calls/master/911.csv")
data

,lat,lng,desc,zip,title,timeStamp,twp,addr,e
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1
5,40.253473,-75.283245,CANNON AVE & W 9TH ST; LANSDALE; Station 345;...,19446.0,EMS: HEAD INJURY,2015-12-10 17:40:01,LANSDALE,CANNON AVE & W 9TH ST,1
6,40.182111,-75.127795,LAUREL AVE & OAKDALE AVE; HORSHAM; Station 35...,19044.0,EMS: NAUSEA/VOMITING,2015-12-10 17:40:01,HORSHAM,LAUREL AVE & OAKDALE AVE,1
7,40.217286,-75.405182,COLLEGEVILLE RD & LYWISKI RD; SKIPPACK; Stati...,19426.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:40:01,SKIPPACK,COLLEGEVILLE RD & LYWISKI RD,1
8,40.289027,-75.399590,MAIN ST & OLD SUMNEYTOWN PIKE; LOWER SALFORD;...,19438.0,EMS: SYNCOPAL EPISODE,2015-12-10 17:40:01,LOWER SALFORD,MAIN ST & OLD SUMNEYTOWN PIKE,1
9,40.102398,-75.291458,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD; PLYM...,19462.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,PLYMOUTH,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD,1
10,40.231990,-75.251891,RT202 PKWY & KNAPP RD; MONTGOMERY; 2015-12-10 ...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,MONTGOMERY,RT202 PKWY & KNAPP RD,1
11,40.084161,-75.308386,BROOK RD & COLWELL LN; PLYMOUTH; 2015-12-10 @ ...,19428.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,PLYMOUTH,BROOK RD & COLWELL LN,1
12,40.174131,-75.098491,BYBERRY AVE & S WARMINSTER RD; UPPER MORELAND;...,19040.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MORELAND,BYBERRY AVE & S WARMINSTER RD,1
13,40.062974,-75.135914,OLD YORK RD & VALLEY RD; CHELTENHAM; 2015-12-1...,19027.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,CHELTENHAM,OLD YORK RD & VALLEY RD,1
14,40.097222,-75.376195,SCHUYLKILL EXPY & CROTON RD UNDERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MERION,SCHUYLKILL EXPY & CROTON RD UNDERPASS,1
15,40.223778,-75.235399,STUMP RD & WITCHWOOD DR; MONTGOMERY; 2015-12-1...,18936.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,MONTGOMERY,STUMP RD & WITCHWOOD DR,1
16,40.243258,-75.286552,SUSQUEHANNA AVE & W MAIN ST; LANSDALE; Statio...,19446.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:46:01,LANSDALE,SUSQUEHANNA AVE & W MAIN ST,1
17,40.312181,-75.574260,CHARLOTTE ST & MILES RD; NEW HANOVER; Station...,19525.0,EMS: DIZZINESS,2015-12-10 17:47:01,NEW HANOVER,CHARLOTTE ST & MILES RD,1
18,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; Station 308A; ...,19401.0,EMS: VEHICLE ACCIDENT,2015-12-10 17:47:01,NORRISTOWN,PENN ST & ARCH ST,1
19,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:47:02,HORSHAM,COUNTY LINE RD & WILLOW DR,1
20,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; 2015-12-10 @ 17...,19401.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:47:02,NORRISTOWN,PENN ST & ARCH ST,1
21,40.117948,-75.209848,CHURCH RD & REDCOAT DR; WHITEMARSH; 2015-12-10...,19031.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:57:02,WHITEMARSH,CHURCH RD & REDCOAT DR,1
22,40.199006,-75.300058,LILAC CT & PRIMROSE DR; UPPER GWYNEDD; 2015-12...,19446.0,Fire: APPLIANCE FIRE,2015-12-10 18:02:01,UPPER GWYNEDD,LILAC CT & PRIMROSE DR,1
23,40.143326,-75.422819,RT422 & PAWLINGS RD OVERPASS; LOWER PROVIDENC...,NaN,Traffic: DISABLED VEHICLE -,2015-12-10 18:02:02,LOWER PROVIDENCE,RT422 & PAWLINGS RD OVERPASS,1
24,40.153268,-75.189558,SUMMIT AVE & RT309 UNDERPASS; UPPER DUBLIN; 20...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:02:02,UPPER DUBLIN,SUMMIT AVE & RT309 UNDERPASS,1
25,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROV...,19403.0,EMS: GENERAL WEAKNESS,2015-12-10 18:06:25,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1
26,40.155283,-75.264230,PENLLYN BLUE BELL PIKE & VILLAGE CIR; WHITPAI...,19422.0,EMS: HEAD INJURY,2015-12-10 18:06:25,WHITPAIN,PENLLYN BLUE BELL PIKE & VILLAGE CIR,1
27,40.028903,-75.351822,EDENTON PL & DURHAM DR; DELAWARE COUNTY; 2015-...,19085.0,Fire: CARBON MONOXIDE DETECTOR,2015-12-10 18:06:25,DELAWARE COUNTY,EDENTON PL & DURHAM DR,1
28,40.097222,-75.376195,SCHUYLKILL EXPY & WEADLEY RD OVERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:06:26,UPPER MERION,SCHUYLKILL EXPY & WEADLEY RD OVERPASS,1
29,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 18:11:01,HORSHAM,COUNTY LINE RD & WILLOW DR,1
...,...,...,...,...,...,...,...,...,...
99462,40.274137,-75.660469,UPLAND SQUARE DR & SELL RD; WEST POTTSGROVE; ...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:41:00,WEST POTTSGROVE,UPLAND SQUARE DR & SELL RD,1
99463,40.254768,-75.660459,SHOEMAKER RD & ROBINSON ST; POTTSTOWN; Statio...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:42:00,POTTSTOWN,SHOEMAKER RD & ROBINSON ST,1
99464,40.163730,-75.082753,KAREN LN & BYBERRY RD; UPPER MORELAND; Statio...,19040.0,EMS: FALL VICTIM,2016-08-24 09:51:06,UPPER MORELAND,KAREN LN & BYBERRY RD,1
99465,40.114928,-75.340307,AIRY ST & GREEN ST; NORRISTOWN; Station 308A;...,19401.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 09:56:13,NORRISTOWN,AIRY ST & GREEN ST,1
99466,40.159820,-75.288436,WENTZ RD & SILO CIR; WHITPAIN; Station 385; 2...,19422.0,EMS: NAUSEA/VOMITING,2016-08-24 10:01:00,WHITPAIN,WENTZ RD & SILO CIR,1
99467,40.255271,-75.340722,WOODS DR & DETWILER RD; TOWAMENCIN; Station 3...,19446.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:12:01,TOWAMENCIN,WOODS DR & DETWILER RD,1
99468,40.088355,-75.382100,DEKALB PIKE & ALLENDALE RD; UPPER MERION; 2016...,19406.0,Fire: FIRE ALARM,2016-08-24 10:12:01,UPPER MERION,DEKALB PIKE & ALLENDALE RD,1
99469,40.123868,-75.341678,MARKLEY ST & JAMES ST; NORRISTOWN; 2016-08-24 ...,19401.0,Fire: FIRE ALARM,2016-08-24 10:12:01,NORRISTOWN,MARKLEY ST & JAMES ST,1
99470,40.185798,-75.536484,WALNUT ST & S 5TH AVE; ROYERSFORD; Station 32...,19468.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:17:01,ROYERSFORD,WALNUT ST & S 5TH AVE,1
99471,40.000763,-75.279769,WYNNEWOOD RD & W OLD WYNNEWOOD RD; LOWER MERI...,19096.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:17:01,LOWER MERION,WYNNEWOOD RD & W OLD WYNNEWOOD RD,1
99472,40.129398,-75.332213,PINE ST & W ROBERTS ST; NORRISTOWN; Station 3...,19401.0,EMS: CARDIAC EMERGENCY,2016-08-24 10:22:00,NORRISTOWN,PINE ST & W ROBERTS ST,1
99473,40.133533,-75.056460,BUCK RD & WAVERLY LN; BRYN ATHYN; Station 355...,19009.0,EMS: GENERAL WEAKNESS,2016-08-24 10:27:01,BRYN ATHYN,BUCK RD & WAVERLY LN,1
99474,40.078678,-75.086943,HUNTINGDON PIKE & FILLMORE ST; ROCKLEDGE; Sta...,19046.0,EMS: SEIZURES,2016-08-24 10:27:01,ROCKLEDGE,HUNTINGDON PIKE & FILLMORE ST,1
99475,40.133715,-75.229630,SHEAFF LN & WHITEMARSH VALLEY RD; WHITEMARSH; ...,19034.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:32:01,WHITEMARSH,SHEAFF LN & WHITEMARSH VALLEY RD,1
99476,40.257820,-75.624294,PARK DR & N ADAMS ST; POTTSTOWN; Station 329;...,19464.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:47:00,POTTSTOWN,PARK DR & N ADAMS ST,1
99477,40.095652,-75.244877,FOX HOUND DR & MARBLE HL; WHITEMARSH; Station...,19444.0,EMS: SUBJECT IN PAIN,2016-08-24 10:47:00,WHITEMARSH,FOX HOUND DR & MARBLE HL,1
99478,40.100344,-75.293955,CHEMICAL RD & GALLAGHER RD; PLYMOUTH; 2016-08-...,19462.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:47:02,PLYMOUTH,CHEMICAL RD & GALLAGHER RD,1
99479,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: CARDIAC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1
99480,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIABETIC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1
99481,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIZZINESS,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1
99482,40.340072,-75.591709,RT100 SB & E PHILADELPHIA AVE OVERPASS; DOUGLA...,NaN,Traffic: DISABLED VEHICLE -,2016-08-24 10:52:03,DOUGLASS,RT100 SB & E PHILADELPHIA AVE OVERPASS,1
99483,40.084465,-75.390173,DEKALB PIKE & KING OF PRUSSIA RD; UPPER MERIO...,19406.0,EMS: BACK PAINS/INJURY,2016-08-24 10:57:00,UPPER MERION,DEKALB PIKE & KING OF PRUSSIA RD,1
99484,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROVI...,19403.0,Fire: FIRE ALARM,2016-08-24 10:57:00,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1
99485,40.143601,-75.427877,EAGLEVILLE RD & REDTAIL RD; LOWER PROVIDENCE; ...,19403.0,Traffic: DISABLED VEHICLE -,2016-08-24 10:57:01,LOWER PROVIDENCE,EAGLEVILLE RD & REDTAIL RD,1
99486,40.179225,-75.180572,WELSH RD & NORRISTOWN RD; HORSHAM; 2016-08-24 ...,19044.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:02:02,HORSHAM,WELSH RD & NORRISTOWN RD,1
99487,40.132869,-75.333515,MARKLEY ST & W LOGAN ST; NORRISTOWN; 2016-08-2...,19401.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:06:00,NORRISTOWN,MARKLEY ST & W LOGAN ST,1
99488,40.006974,-75.289080,LANCASTER AVE & RITTENHOUSE PL; LOWER MERION; ...,19003.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:07:02,LOWER MERION,LANCASTER AVE & RITTENHOUSE PL,1
99489,40.115429,-75.334679,CHESTNUT ST & WALNUT ST; NORRISTOWN; Station ...,19401.0,EMS: FALL VICTIM,2016-08-24 11:12:00,NORRISTOWN,CHESTNUT ST & WALNUT ST,1
99490,40.186431,-75.192555,WELSH RD & WEBSTER LN; HORSHAM; Station 352; ...,19002.0,EMS: NAUSEA/VOMITING,2016-08-24 11:17:01,HORSHAM,WELSH RD & WEBSTER LN,1
99491,40.207055,-75.317952,MORRIS RD & S BROAD ST; UPPER GWYNEDD; 2016-08...,19446.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:17:02,UPPER GWYNEDD,MORRIS RD & S BROAD ST,1

Problem 1:
#Describe for cat and numerical column

In [13]:
data.dtypes

lat          float64
lng          float64
desc          object
zip          float64
title         object
timeStamp     object
twp           object
addr          object
e              int64
dtype: object

In [11]:
data.describe()

                lat           lng           zip        e
count  99492.000000  99492.000000  86637.000000  99492.0
mean      40.159526    -75.317464  19237.658298      1.0
std        0.094446      0.174826    345.344914      0.0
min       30.333596    -95.595595  17752.000000      1.0
25%       40.100423    -75.392104  19038.000000      1.0
50%       40.145223    -75.304667  19401.000000      1.0
75%       40.229008    -75.212513  19446.000000      1.0
max       41.167156    -74.995041  77316.000000      1.0

In [14]:
data.dtypes=="object"

lat          False
lng          False
desc          True
zip          False
title         True
timeStamp     True
twp           True
addr          True
e            False
dtype: bool

In [17]:
data.dtypes=="object"
a=data.dtypes[data.dtypes=="object"].index
a
data[a].describe()

,desc,title,timeStamp,twp,addr
count,99492,99492,99492,99449,98973
unique,99455,110,72577,68,21914
top,GREEN ST & E BASIN ST; NORRISTOWN; Station 30...,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,LOWER MERION,SHANNONDELL DR & SHANNONDELL BLVD
freq,4,23066,8,8443,938

Problem 2:
#lat type cast it to int, perform group by and apply count on it

In [25]:
data["lat"]=data["lat"].apply(int)
data.head()

,lat,lng,desc,zip,title,timeStamp,twp,addr,e
0,40,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1
1,40,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1
2,40,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1
3,40,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1
4,40,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1

Problem 3
#how many people are from same zip location

In [29]:
d2=data.groupby(["zip"]).size().reset_index(name="number of people")
d2.head()

       zip  number of people
0  17752.0                 1
1  18036.0                 2
2  18041.0               414
3  18054.0               326
4  18056.0                 6

Problem 4
#check time stamp datatype and extract day in new col

In [60]:
data['day'] = pd.DatetimeIndex(data['timeStamp']).day
data.head()

,lat,lng,desc,zip,title,timeStamp,twp,addr,e,mon_sun,day
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1,NaT,10
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1,NaT,10
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1,NaT,10
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1,NaT,10
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1,NaT,10

Problem 5
#filter out all the zip codes which address starts with 'A'

In [23]:
import numpy as np
df=data[data['desc'].str.startswith('A')]  
df
df2=df[["desc","zip"]]
df2.head()

                                                  desc      zip
3    AIRY ST & SWEDE ST;  NORRISTOWN; Station 308A;...  19401.0
43   ALLENDALE RD & WILLS BLVD; UPPER MERION; 2015-...  19406.0
48   AUTO PARK BLVD & LINFIELD TRAPPE RD; LIMERICK;...  19468.0
72   AVIGNON DR & DEAD END; LOWER MERION; 2015-12-1...      NaN
103  ADAMS ST & WALNUT ST; ROYERSFORD; 2015-12-10 @...  19468.0

problem 6
6) from title extract service detail

In [80]:
data.dtypes=="object"
a=data.dtypes[data.dtypes=="object"].index
a
data[a].describe()

,desc,title,timeStamp,twp,addr
count,99492,99492,99492,99449,98973
unique,99455,110,72577,68,21914
top,GREEN ST & E BASIN ST; NORRISTOWN; Station 30...,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,LOWER MERION,SHANNONDELL DR & SHANNONDELL BLVD
freq,4,23066,8,8443,938

In [81]:
data["title"].describe()

count                           99492
unique                            110
top       Traffic: VEHICLE ACCIDENT -
freq                            23066
Name: title, dtype: object